/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 13-may.-2026 16:39:43 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS aproduc CASCADE
;

/* Create Tables */

CREATE TABLE aproduc
(
	paproduccodprod character varying(30) NOT NULL,
	caproduccosprod numeric(20),
	caproduccolprod character varying(50),
	caproducnomprod character varying(30),
	caproducpreprod numeric(20),
	caproducstkprod character varying(20),
	caproductalprod character varying(50),
	caproductipprod character varying(20),
	CONSTRAINT PK_Table1 PRIMARY KEY (paproduccodprod)
)
;
